### ISSUE TITLE
Feature: ARM64 builds

### ISSUE THREAD

**Issue by scottslowe** [boz/kail#64] opened 2021-07-30 02:57 UTC
It would be great to get ARM64 builds for Linux and macOS (Darwin). I tried a quick compile of ARM64 for macOS and it seemed to work without any noticeable issues.

**Comment by mnaser** [comment] 2021-12-03 07:58
This has been addressed by #63 it seems.

**Comment by mnaser** [comment] 2022-08-16 21:08
@boz could we close this (also I can help in trimming up the repository/maintaining if you'd like)

**Comment by manuel-koch** [comment] 2022-09-29 10:18
Although #63 seems to be closed, I can't install the "krew" plugin "tail" because the arm64 binary seems to be missing.

```
$ kubectl krew install tail
Updated the local copy of plugin index.
Installing plugin: tail
W0929 12:08:26.850932   43794 install.go:164] failed to install plugin "tail": plugin "tail" does not offer installation for this platform
failed to install some plugins: [tail]: plugin "tail" does not offer installation for this platform
```

Latest [release](https://github.com/boz/kail/releases/tag/v0.15.0) of kail doesn't include arm64 binary either.

**Comment by zouchengli** [comment] 2022-10-13 09:00
> 
Download for here.
[kail_darwin_arm64.tar.gz](https://github.com/boz/kail/files/9774780/kail_darwin_arm64.tar.gz)

**Comment by HAND-zouchengli** [comment] 2022-10-25 23:23
> How can this tar be used when installing the plugin using something like kubectl krew install tail ?

You just download arm64(darwin) binary.

**Comment by zouchengli** [comment] 2022-10-26 00:34
> How can this tar be used when installing the plugin using something like `kubectl krew install tail` ?

This requires the author to release the new arm64 (darwin) package, I just temporarily compiled a package that can be decompressed for you. Why do you have to install kail command this way?

**Comment by zouchengli** [comment] 2022-10-26 02:58
> How can this tar be used when installing the plugin using something like `kubectl krew install tail` ?

<img width="710" alt="image" src="https://user-images.githubusercontent.com/27568522/197924146-0a8a6c5c-2e5b-4896-ac30-bb7684c00577.png">

**Comment by manuel-koch** [comment] 2022-10-26 07:28
> Why do you have to install kail command this way?

Because the krew plugin suggest to install it that way - I want to use the krew plugin ( not necessarily some other binary ).
I'm sure I can use that compiled binary, but then it is not usable as a krew plugin ( at least not for me as a naive user of krew plugins ).

**Comment by zouchengli** [comment] 2022-10-26 07:55
> Because the krew plugin suggest to install it that way - I want to use the krew plugin ( not necessarily some other binary ).
> I'm sure I can use that compiled binary, but then it is not usable as a krew plugin ( at least not for me as a naive user of krew plugins ).

This has been addressed by https://github.com/boz/kail/pull/63 it seems.

**Comment by manuel-koch** [comment] 2022-10-26 08:23
I guess the `krew tail` plugin can only be updated when a release of `kail` is available that includes arm64 binary.

**Comment by mnaser** [comment] 2022-11-14 21:47
Duplicate of https://github.com/boz/kail/issues/68

**Closed by mnaser** 2022-11-14 21:47 UTC
